name: myberikan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  intl: ^0.18.0
  excel: ^4.0.2
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^17.0.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ðŸ”¥ FIREBASE (WAJIB DI SINI)
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.0

  # UTIL
  image_picker: ^1.2.1
  crypto: ^3.0.3
  fl_chart: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutterfire_cli: ^1.3.1
  collection: ^1.19.1
  flutter_image_compress: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Poppins_Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins_Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins_Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins_SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
